### ISSUE TITLE
Exception error "Failed to create projection for authority: EPSG, code: 3857" in the Android logcat for Pseudo Mercator projection

### ISSUE THREAD

**Issue by eclectice** [ngageoint/geopackage-mapcache-android#49]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage MapCache Android Version: 2.1.1
  * GeoPackage MapCache Android Source: (e.g. Release APK, Source Code Build): Google Play Store
  * Device or Emulator: Samsung Note 5 (SM-N9208)
  * Android Version Number: 7.0
  * Google Play services Version: 22.12.55 (040400-439688370)
  * Android Studio Version (if applicable):
  * Platform & OS: Android 7.0
  * Other Relevant Libraries:
  
#### Expected Results:

  * What did you expect to happen? 
  No exception in the logcat when loading a raster Geopackage file with Pseudo Mercator projection

#### Observed Results:

  * What happened instead? 
  Despite the fact that the map is displayed when it is enabled after it is loaded, an error appears in the Android logcat twice while loading it. I'm curious as to why it displays such an error.

  * How often does this occur? 
  It occurs whenever a new raster Geopackage file with Pseudo Mercator projection is attempted to be loaded into Mapcache. It also happens with previously loaded maps (with Pseudo Mercator projection) when the Mapcache is launched from the beginning.

#### Output:

  * Any logs, errors, or output messages?
   <details><summary>Logcat</summary>

```
2022-04-11 09:24:08.348 19309-19942/? W/ProjectionFactory: Failed to create projection for authority: EPSG, code: 3857, definition: 
                    PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984"
                    ,SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]]
                    ,AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG",
                    "8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]
                    ,AUTHORITY["EPSG","9122"]]AUTHORITY["EPSG","4326"]],PROJECTION[
                    "Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER[
                    "scale_factor",1],PARAMETER["false_easting",0],PARAMETER[
                    "false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS[
                    "X",EAST],AXIS["Y",NORTH]
                
    mil.nga.crs.CRSException: Unexpected end of text, null token
        at mil.nga.crs.wkt.TextReader.readExpectedToken(TextReader.java:318)
        at mil.nga.crs.wkt.CRSReader.readRightDelimiter(CRSReader.java:1159)
        at mil.nga.crs.wkt.CRSReader.readProjectedCompat(CRSReader.java:4097)
        at mil.nga.crs.wkt.CRSReader.readProjectedCompat(CRSReader.java:3996)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:812)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:117)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:99)
        at mil.nga.proj.ProjectionFactory.fromDefinition(ProjectionFactory.java:988)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:650)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:582)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:536)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:454)
        at mil.nga.geopackage.srs.SpatialReferenceSystem.getProjection(SpatialReferenceSystem.java:355)
        at mil.nga.geopackage.tiles.matrixset.TileMatrixSet.getProjection(TileMatrixSet.java:268)
        at mil.nga.geopackage.tiles.user.TileDao.<init>(TileDao.java:92)
        at mil.nga.geopackage.GeoPackageImpl.getTileDao(GeoPackageImpl.java:262)
        at mil.nga.geopackage.GeoPackageImpl.getTileDao(GeoPackageImpl.java:336)
        at mil.nga.mapcache.repository.GeoPackageRepository.regenerateTableList(GeoPackageRepository.java:457)
        at mil.nga.mapcache.viewmodel.GeoPackageViewModel.regenerateGeoPackageTableList(GeoPackageViewModel.java:458)
        at mil.nga.mapcache.viewmodel.GeoPackageViewModel.importGeoPackage(GeoPackageViewModel.java:630)
        at mil.nga.mapcache.load.ImportTask$ImportGeoTask.doInBackground(ImportTask.java:456)
        at mil.nga.mapcache.load.ImportTask$ImportGeoTask.doInBackground(ImportTask.java:321)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
2022-04-11 09:24:08.352 19309-19942/? W/ProjectionFactory: Failed to create projection for authority: EPSG, code: 3857, definition: 
                    PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984"
                    ,SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]]
                    ,AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG",
                    "8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]
                    ,AUTHORITY["EPSG","9122"]]AUTHORITY["EPSG","4326"]],PROJECTION[
                    "Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER[
                    "scale_factor",1],PARAMETER["false_easting",0],PARAMETER[
                    "false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS[
                    "X",EAST],AXIS["Y",NORTH]
                
    mil.nga.crs.CRSException: Unexpected end of text, null token
        at mil.nga.crs.wkt.TextReader.readExpectedToken(TextReader.java:318)
        at mil.nga.crs.wkt.CRSReader.readRightDelimiter(CRSReader.java:1159)
        at mil.nga.crs.wkt.CRSReader.readProjectedCompat(CRSReader.java:4097)
        at mil.nga.crs.wkt.CRSReader.readProjectedCompat(CRSReader.java:3996)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:812)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:117)
        at mil.nga.crs.wkt.CRSReader.read(CRSReader.java:99)
        at mil.nga.proj.ProjectionFactory.fromDefinitionParams(ProjectionFactory.java:1030)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:654)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:582)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:536)
        at mil.nga.proj.ProjectionFactory.getProjection(ProjectionFactory.java:454)
        at mil.nga.geopackage.srs.SpatialReferenceSystem.getProjection(SpatialReferenceSystem.java:355)
        at mil.nga.geopackage.tiles.matrixset.TileMatrixSet.getProjection(TileMatrixSet.java:268)
        at mil.nga.geopackage.tiles.user.TileDao.<init>(TileDao.java:92)
        at mil.nga.geopackage.GeoPackageImpl.getTileDao(GeoPackageImpl.java:262)
        at mil.nga.geopackage.GeoPackageImpl.getTileDao(GeoPackageImpl.java:336)
        at mil.nga.mapcache.repository.GeoPackageRepository.regenerateTableList(GeoPackageRepository.java:457)
        at mil.nga.mapcache.viewmodel.GeoPackageViewModel.regenerateGeoPackageTableList(GeoPackageViewModel.java:458)
        at mil.nga.mapcache.viewmodel.GeoPackageViewModel.importGeoPackage(GeoPackageViewModel.java:630)
        at mil.nga.mapcache.load.ImportTask$ImportGeoTask.doInBackground(ImportTask.java:456)
        at mil.nga.mapcache.load.ImportTask$ImportGeoTask.doInBackground(ImportTask.java:321)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

</details>

#### Steps to Reproduce:

  1. Load any raster Geopackage file with Pseudo Mercator projection

#### Test Files:

  * Links to any files needed for testing? 
  Due to non-disclosure with the government entity, I am unable to release my raster Geopackage file that uses Pseudo Mercator projection. However, I can offer a few necessary tables using the SQLite DB Browser:

   <details><summary>DB Browser for SQLite tables</summary>

 * gpkg_contents

![image](https://user-images.githubusercontent.com/1452656/162651267-deb3906a-7990-44d9-a70d-68bc436e7eab.png)

 * gpkg_spatial_ref_sys

![image](https://user-images.githubusercontent.com/1452656/162652358-06e9681c-a425-4218-a0db-6d692841a43f.png)

   </details>

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?
  None

**Comment by bosborn** [comment]
The Coordinate Reference System Well-Known Text in your GeoPackage(`gpkg_spatial_ref_sys` `definition`) does not appear to be valid.  There is fallback logic for failed and/or invalid definitions.  In your case, the error is logged and the projection is successfully retrieved through an authority/code lookup.  Projections are cached to reduce re-parsing matching authority, code, and definitions.

Invalid:
```
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","9122"]]
    AUTHORITY["EPSG","4326"]],
PROJECTION["Mercator_1SP"],
PARAMETER["central_meridian",0],
PARAMETER["scale_factor",1],
PARAMETER["false_easting",0],
PARAMETER["false_northing",0],
UNIT["metre",1,
    AUTHORITY["EPSG","9001"]],
AXIS["X",EAST],
AXIS["Y",NORTH]
```

Valid (by fixing the provided invalid, other valid versions exist):

* Remove 2nd occurrence of 'AUTHORITY["EPSG","9122"]]'
* Add an overall closing bracket

```
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH]]
```

If you have control over the GeoPackage creation, update the definition.  If you are provided the GeoPackage, I suggest contacting/informing the producer.

**Comment by bosborn** [comment]
EPSG 3857 is a special case that [relies on the equator radius instead of the known ellipsoid](https://github.com/ngageoint/projections-java/blob/d3d2b35b5f90c7d70d5619f0233a53763d6e1745/src/main/java/mil/nga/proj/CRSParser.java#L268).  Add `AUTHORITY["EPSG","3857"]` at the end of the CRS WKT to fix the projections.

```
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH],
    AUTHORITY["EPSG","3857"]]
```

#### [Project](https://github.com/ngageoint/projections-java/tree/master/script/project) Output for coordinate [12310642.027497, 181232.194064]:

   <details><summary>w/o AUTHORITY["EPSG","3857"]</summary>

$ proj

From Projection: PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH]]

To Projection: 4326

PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH]]
->
EPSG:4326

Enter 'Inverse' to invert transformation

Coordinate(s): 12310642.027497,181232.194064

[12310642.027497, 181232.194064] -> [110.58837890624689, **1.6387821648748968**]

   </details>

   <details><summary>w/ AUTHORITY["EPSG","3857"]</summary>

$ proj

From Projection: PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH]**,
    AUTHORITY["EPSG","3857"]**]

To Projection: 4326

EPSG:3857 -> EPSG:4326

Enter 'Inverse' to invert transformation

Coordinate(s): 12310642.027497,181232.194064

[12310642.027497, 181232.194064] -> [110.58837890624689, **1.6278174666801366**]

   </details>

**Comment by eclectice** [comment]
Wow, it's so simple once I learn about it. Thank you; it now works as intended, as shown below. I can finally rest in peace.

![device-2022-04-13-091751](https://user-images.githubusercontent.com/1452656/163080090-50016546-671c-4202-945b-2c02db971c13.png)
